Develop
esper-io/console_docs pull request #12
Opened 2021-06-17 17:37 UTC by radhak21

Added storage setting under Esper setting and added a note for tags drop-down.

2021-06-18 05:25 UTC, kirananto submitted a review, later dismissed

2021-06-18 16:27 UTC, ankitgupta29 approved these changes

2021-06-18 17:45 UTC, kzotter requested changes
Capitalize Bluetooth

2021-06-18 17:45 UTC, kzotter approved these changes

2021-06-18 17:46 UTC, kzotter approved these changes

2021-06-18 17:46 UTC, kzotter approved these changes

2021-06-22 04:32 UTC, VineethaVR reviewed
Why are we adding a link to old docs page? It should be relative to the new docs.

"Factory Reset Protection (FRP) places an auto-lock on a GMS-certified device if a user factory resets it with soft or hard keys. FRP will auto-lock the device and keep it locked until a pre-authorized Google account ID is entered. Additional information about getting your Google Account ID can be found in the [here](https://docs.esper.io/home/console/policy-management/getgoogleaccount.html#how-to-get-google-id-and-use-frp-factory-reset-protection-feature)."

2021-06-22 21:04 UTC, colesper approved these changes

2021-06-22 21:07 UTC, colesper commented on docs/compliance-policy/frp.md
> +As a result, an unauthorized user can not simply factory reset your device and use it against your permission.
Change "can not" to "cannot"

2021-06-22 21:08 UTC, colesper requested changes
Commented in-line. But "can not" should be "cannot".

2021-06-23 04:04 UTC, VineethaVR approved these changes

2021-06-23 11:20 UTC, colesper approved these changes

2021-06-23 11:47 UTC, ankitgupta29 commented on docs/compliance-policy/create-policy.md
> +- Storage: Helps to grant permissions to any directories on the device. On devices running Android 10 or below, it is advised that the admins inform the users to grant permissions to the root folder.
Console admin informs the device users

2021-06-23 12:06 UTC, ankitgupta29 commented on docs/compliance-policy/create-policy.md
> +- Storage: Helps to grant permissions to any directories on the device. On devices running Android 10 or below, it is advised that the admins inform the users to grant permissions to the root folder.
root folder? Can we specify example what does this mean like /sdcard/ etc?

2021-06-23 12:06 UTC, ankitgupta29 commented on docs/compliance-policy/create-policy.md
> +-   Bluetooth: Navigate to Android settings on the Android 8.1 and lower devices to change the Bluetooth setting.
Navigate to the Android System Settings app

2021-06-23 12:06 UTC, ankitgupta29 commented on docs/compliance-policy/create-policy.md
> +If you would like the device user to use bluetooth on the device, set the bluetooth toggle button to On; if you don’t, set it to Off.
bluetooth ->Bluetooth

2021-06-23 12:06 UTC, ankitgupta29 commented on docs/content-management/transfer.md
> +You can append the path with the "forced/" keyword ("forced/storage/emulated/0/Esper/NewFolder/"), which will ask users permission for that directory (if the directory exists). On granting access, th
add example

You can append the path with the "forced/" keyword (example: "forced/storage/emulated/0/Esper/NewFolder/")

2021-06-28 05:39 UTC, VineethaVR approved these changes

2021-06-28 15:28 UTC, merged